### PR TITLE
Unix domain socket

### LINKED ISSUE #33: Unix Socket support
Hey! Is it possible to use Statix with a unix socket?

### PR DESCRIPTION
**Pull request by benwilson512**
Note, this is based off of the formatted PR.

Fixes #33

### CODE REVIEW

**Comment by benwilson512** [comment]
I can confirm that we have this working happily in production.

**Comment by lexmag** [comment]
Great work @benwilson512.
The formatted PR is merged, could you rebase on master?

**Comment by benwilson512** [comment]
Did the format branch get force pushed? I'm having a lot of trouble reconciling the git history

**Comment by lexmag** [comment]
@benwilson512 there were 2 extra commits: 63a8d8f5a594c323a136b5f96d6ce58492fe7d8e and c7110a60bba5306f297230dda04ebd66bacf1057.

**Pull request closed without merging**
