### PR TITLE
Events & Service checks

### PR DESCRIPTION
**Pull request by rodrigues**
This PR adds the much wanted access to datadog statsd extensions from statix:

Events: https://docs.datadoghq.com/developers/dogstatsd/#events-1
Service checks: https://docs.datadoghq.com/developers/dogstatsd/#service-checks-1

This basically is a sync https://github.com/lexmag/statix/pull/14 from @visciang with latest master.

### CODE REVIEW

**Comment by rodrigues** [comment]
@lexmag if you'd rather not add these extensions, could we make the function `Statix.Conn.transmit(packet, sock)` a public function?

Now it's private, and opening just that function, would make it so much easier to extend 👍🏼

**Comment by aspett** [comment]
👍 Keen to see this make it's way in

**Comment by Jcambass** [comment]
@bravely @rodrigues I'd really like to see to this getting merged. Are there any blockers?

**Comment by rodrigues** [comment]
@Jcambass I've recently updated this PR with the latest changes in master. I didn't spot any missing issues, although I'm not running this code in production. If you wanna review this code, it will be much appreciated 👍🏼

**Comment by bionicpill** [comment]
@rodrigues, is there a reason this was closed without ever being merged? It seems like a desired feature, but I could understand if it is out of scope for Statix because of its specific ties to Datadog. However, if that's the case it would be nice to know, and maybe create a Datadog specific fork of Statix so this feature could be used by those who desire it.

**Comment by rodrigues** [comment]
@bionicpill hi, I’ve closed this due to inactivity, feel free to use this as you wish 😁👍

**Pull request closed without merging**
