### PR TITLE
Updated measure to return the result of the given function

### PR DESCRIPTION
**Pull request by forest**
This enables pipelining and easily wrapping code that needs to return a result.

### CODE REVIEW

**Comment by lexmag** [comment]
Thank you. :yellow_heart:

**Comment by localshred** [comment]
Stoked to see this get merged! Any idea when this will get released out to hex? Thanks! :two_hearts:

**Comment by lexmag** [comment]
@localshred it is on Hex (as v0.7.0).

**Comment by localshred** [comment]
Thanks @lexmag and @forest!

**Pull request merged**
